name: Kubescape Scan on Minikube

on:
  push:
    

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: 'v1.23.3'

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.23.3'

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | bash -s -- -d ./
          export PATH=$PATH:$(pwd)
          export PATH=$PATH:/home/runner/.kubescape/bin
          kubescape scan framework nsa -v --format json --output results.json
      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install tabulate
      - name: Convert Kubescape JSON to Markdown Table (using Python)
        run: |
          python3 .github/workflows/kubescape_to_markdown.py results.json > results.md
      - name: Upload Kubescape Report
        uses: actions/upload-artifact@v4
        with:
          name: Kubescape_Report
          path: results.md

      - name: Output results to Summary
        if: always()
        run: |
          cat results.md >> $GITHUB_STEP_SUMMARY
      - name: Upload results.json
        uses: actions/upload-artifact@v4
        with:
          name: Kubescape_JSON_Output
          path: results.json