name: Kubescape Scan on Minikube

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: 'v1.23.3'

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.23.3'

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | bash -s -- -d ./
          export PATH=$PATH:$(pwd)
          export PATH=$PATH:/home/runner/.kubescape/bin
          kubescape scan framework nsa -v --format json --output results.json

      - name: Convert JSON to SARIF
        uses: garethr/snyk-to-sarif@master
        with:
          input: results.json
          output: results.sarif

      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Upload Raw JSON Results
        uses: actions/upload-artifact@v4
        with:
          name: Kubescape_JSON_Output
          path: results.json
