name: Scan Minikube Cluster with Kubescape

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          version: 'latest'
          kubernetes-version: 'v1.28.0'

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          install-latest: true

      # - name: Install Kubescape
      #   run: |
      #     curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | bash -s -- -d ./
      #     export PATH=$PATH:$(pwd)
      #     export PATH=$PATH:/home/runner/.kubescape/bin
      #     kubescape scan framework nsa -v --format json --output results.json
      - name: Install kubescape and scan cluster
        uses: kubescape/github-action@main
        continue-on-error: true
        with:
          format: json
          outputFile: results
          frameworks: |
            nsa,mitre

      # - name: Convert JSON to HTML Table
      #   id: json_to_html
      #   uses: Teebra/JSON-to-HTML-table@v2.0.0
      #   with:
      #     json-file: results.json
      #     # Optional: You can customize the table styling.
      #     # style: |
          #   .table-class {
          #     border-collapse: collapse;
          #     width: 100%;
          #   }
          #   .table-class th, .table-class td {
          #     border: 1px solid #ddd;
          #     padding: 8px;
          #     text-align: left;
          #   }
          #   .table-class th {
          #     background-color: #f0f0f0;
          #   }
          #   .table-class tr:nth-child(even) {
          #     background-color: #f2f2f2;
          #   }
          
      # - name: Add Results to Summary
      #   run: |
      #     echo "## Kubescape Scan Results" >> $GITHUB_STEP_SUMMARY
      #     # Check if the conversion produced a table.
      #     if [[ -n "${{ steps.json_to_html.outputs.html }}" ]]; then
      #       echo "${{ steps.json_to_html.outputs.html }}" >> $GITHUB_STEP_SUMMARY
      #     else
      #       echo "No results to display or error converting to HTML.  Check 'results.json'" >> $GITHUB_STEP_SUMMARY
      #     fi
      


      - name: Convert JSON to HTML Table
        uses: Teebra/JSON-to-HTML-table@v2.0.0
        with:
          json-file: results.json
      
      - name: Upload HTML Table to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output_html 
          path: output.html # The created file's name is output.html. Name cannot be changed
