name: Kubescape Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kubescape_scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write # Required for SARIF output if you choose that format

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: 'latest'

      - name: Wait for Minikube to be Ready
        run: kubectl wait --for=condition=ready node/minikube --timeout=60s
        
      - name: Run Kubescape Scan
        uses: kubescape/github-action@main
        with:
          format: text # Or try 'sarif' for GitHub Code Scanning
          outputFile: kubescape-report # Optional, but can be useful for debugging

      - name: Add Kubescape Report to Summary
        if: always() # Ensure this runs even if the scan fails (adjust as needed)
        run: |
          if [ -f kubescape-report ]; then
            report=$(cat kubescape-report)
            echo "## Kubescape Scan Summary" >> $GITHUB_STEP_SUMMARY
            echo "$report" >> $GITHUB_STEP_SUMMARY
          else
            echo "## Kubescape Scan Summary" >> $GITHUB_STEP_SUMMARY
            echo "No Kubescape report found." >> $GITHUB_STEP_SUMMARY
          fi