name: Kubescape Scan and GitHub Summary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kubescape_scan_summary:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: 'latest'

      - name: Wait for Minikube to be Ready
        run: kubectl wait --for=condition=ready node/minikube --timeout=60s

      - name: Install Kubescape (if not already present)
        run: |
          if ! command -v kubescape &> /dev/null; then
            curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | sudo bash
          fi
          kubescape version

      - name: Run Kubescape Scan and Generate JSON Report
        id: run_kubescape_scan
        run: |
          kubescape scan framework nsa -v --format json --output kubescape_report.json
          # Check the output of the Kubescape scan
          if [ ! -s "kubescape_report.json" ]; then
            echo "Error: kubescape_report.json is empty or does not exist.  The Kubescape scan may have failed."
            exit 1
          else
            echo "Kubescape scan completed successfully. Output written to kubescape_report.json"
            cat kubescape_report.json
          fi

      - name: Summarize Kubescape Scan Results
        if: success()
        run: |
          # Install jq
          sudo apt-get update
          sudo apt-get install -y jq

          # Read the JSON report
          report_json=$(cat kubescape_report.json)

          # Extract summary information using jq with null checks
          summary=$(echo "$report_json" | jq -r '
            if (.Summary.TotalResources != null and .Summary.FailedResources != null) then
              {
                "total_controls": .Summary.TotalResources,
                "failed_controls": .Summary.FailedResources,
                "passed_controls": (.Summary.TotalResources - .Summary.FailedResources),
                "compliance_percentage": (100 - (.Summary.FailedResources / .Summary.TotalResources * 100))
              }
            else
              {
                "total_controls": 0,
                "failed_controls": 0,
                "passed_controls": 0,
                "compliance_percentage": 0
              }
            end
          ')

          # Output the summary to GitHub Actions summary
          echo "## Kubescape Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Total Controls | Failed Controls | Passed Controls | Compliance |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|---|---| " >> $GITHUB_STEP_SUMMARY
          echo "| $(echo "$summary" | jq -r .total_controls) | $(echo "$summary" | jq -r .failed_controls) | $(echo "$summary" | jq -r .passed_controls) | $(echo "$summary" | jq -r .compliance_percentage | printf '%.2f%%') |" >> $GITHUB_STEP_SUMMARY
          

          # Extract and output detailed results for each failed control
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Failed Controls" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Filter and get failed results as a JSON array
          failed_results_json=$(echo "$report_json" | jq '.Results | if . == null then [] else .[] | select(.Status == "failed") end')

          # Use jq to iterate and format the output
          if [[ $(echo "$failed_results_json" | jq length) -gt 0 ]]; then
            echo "| Severity | Control Name | Docs | Assisted Remediation |" >> $GITHUB_STEP_SUMMARY
            echo "|---|---|---|---| " >> $GITHUB_STEP_SUMMARY
            echo "$failed_results_json" | jq -r '.[] | "\(.Severity) | \(.Name) | [Link](https://hub.armosec.io/docs/\(.ControlID)) | \(.Remediation) |"' >> $GITHUB_STEP_SUMMARY
          else
            echo "No failed controls found." >> $GITHUB_STEP_SUMMARY
          fi
