name: Slack Notification Test

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel-id: 'C08RG8A30M9'
          slack-message: 'Hello from GitHub Actions!'