name: Kubescape Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kubescape_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: 'latest'

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | sudo bash
          kubescape version

      - name: Run Kubescape on Minikube
        id: kubescape-scan-cluster
        run: kubescape scan framework nsa -v --format json --output results.json

      # - name: Format Kubescape Results for Slack
      #   id: format-results
      #   run: |
      #     if [ -f results.json ]; then
      #       report=$(cat results.json | jq -c '.summaryDetails.controls | to_entries[] | "*Rule:* \(.value.name), *Status:* \(.value.status), *Category:* \(.value.category.name), *Score:* \(.value.score)"' | paste -sd "\n")
      #       echo "::set-output name=slack_report::$report"
      #     else
      #       echo "::set-output name=slack_report::No Kubescape results found."
      #     fi

      # - name: Send Kubescape Report to Slack
      #   if: always()
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SLACK_CHANNEL_ID: 'C08RG8A30M9'
      #   run: |
      #     payload='{"channel":"$SLACK_CHANNEL_ID","text":"Test"}'
      #     curl -X POST -H 'Content-type: application/json' \
      #     --data "$payload" \
      #     "$SLACK_WEBHOOK_URL"

      - name: Run Kubescape on Minikube and Generate Summary
        id: kubescape-summary
        run: |
          summary=$(kubescape scan framework nsa -v --format text)
          echo "::set-output name=report::$summary"

      - name: Add Kubescape Report to Summary
        run: |
          echo "## Kubescape Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.kubescape-summary.outputs.report }}" >> $GITHUB_STEP_SUMMARY