name: Slack Notification

on:
  push:
    branches:
      - main

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: 'C08RG8A30M9'
          slack-text: |
            :tada: A new commit has been pushed to the `main` branch!
            Commit message: ${{ github.event.head_commit.message }}
            Commit author: ${{ github.event.head_commit.author.name }}
            Commit URL: ${{ github.event.head_commit.url }}