name: Kubescape Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kubescape_scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: 'latest'

      - name: Wait for Minikube to be Ready
        run: kubectl wait --for=condition=ready node/minikube --timeout=60s

      - name: Install Kubescape (if not already present)
        run: |
          if ! command -v kubescape &> /dev/null; then
            curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | sudo bash
          fi
          kubescape version

      - name: Run Kubescape Scan
        id: kubescape-scan
        run: |
          kubescape scan --format pretty-printer > kubescape_report.txt
          report=$(cat kubescape_report.txt | sed -e 's/\x1B\[[0-9;]*[mG]//g')
          echo "report=$report" >> "$GITHUB_OUTPUT"

      - name: Add Kubescape Report to Summary
        run: |
          echo "## Kubescape Scan Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f kubescape_report.txt ]; then
            report_content=$(cat kubescape_report.txt | sed -e 's/\x1B\[[0-9;]*[mG]//g')
            echo "$report_content" >> $GITHUB_STEP_SUMMARY
          else
            echo "No Kubescape report file found." >> $GITHUB_STEP_SUMMARY
          fi